# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.6.0'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install'

- task: Npm@1
  displayName: 'Run tests'
  inputs:
    command: 'custom'
    workingDir: './'
    customCommand: 'run test'

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/coverage/jest/cobertura-coverage.xml'
    reportDirectory: '$(System.DefaultWorkingDirectory)/coverage'

- script: |
    npm run build-backend
  displayName: 'Build backend'

- script: |
    npm run build-frontend
  displayName: 'Build frontend'
  
- task: CopyFiles@2
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)/dist'
    contents: '*.tgz' 
    targetFolder: $(Build.ArtifactStagingDirectory)/npm-backend
  displayName: 'Copy npm package for backend'

- task: CopyFiles@2
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)/build'
    contents: '*.tgz' 
    targetFolder: $(Build.ArtifactStagingDirectory)/npm-frontend
  displayName: 'Copy npm package for frontend'

- task: CopyFiles@2
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)'
    contents: 'package.json' 
    targetFolder: $(Build.ArtifactStagingDirectory)/npm-backend
  displayName: 'Copy package.json for backend'

- task: CopyFiles@2
  inputs:
    sourceFolder: '$(Build.SourcesDirectory)'
    contents: 'package.json' 
    targetFolder: $(Build.ArtifactStagingDirectory)/npm-frontend
  displayName: 'Copy package.json for frontend'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)/npm-backend'
    artifactName: backend
  displayName: 'Publish backend artifact'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)/npm-frontend'
    artifactName: frontend
  displayName: 'Publish frontend artifact'

