version: "3.2"
services:
  sep-db:
    container_name: sep-db
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "SuperS3cret!"
      ACCEPT_EULA: "Y"
    volumes:
      - ./tmp:/var/opt/mssql
