import { createApp } from '../src/backend/index';
import supertest from 'supertest';
import { seedTables } from './mocks/mock-db';
require('dotenv').config({ path: '.env.testing' })

// Fake expired token used alongside BYPASS_AUTH env variable. For user ID 774d6f78-5477-4f71-8f6e-fea599577a50
const fakeIdToken = `eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IjJaUXBKM1VwYmpBWVhZR2FYRUpsOGxWMFRPSSJ9.eyJhdWQiOiI0NWNiMzU1NS1hZDdjLTQwYWQtYWQ0OC0zMTQ0MjhkZDJiMjgiLCJpc3MiOiJodHRwczovL2xvZ2luLm1pY3Jvc29mdG9ubGluZS5jb20vM2RjN2E4ZDMtMmRiYS00NDQ4LWFkZDItZmJkOTNmMDhmYTRmL3YyLjAiLCJpYXQiOjE2NjQyOTk1NDEsIm5iZiI6MTY2NDI5OTU0MSwiZXhwIjoxNjY0MzAzNDQxLCJlbWFpbCI6ImplZy1hZG1pbkB5NHRrMi5vbm1pY3Jvc29mdC5jb20iLCJmYW1pbHlfbmFtZSI6IkNhdWRpbGwiLCJnaXZlbl9uYW1lIjoiSm9yZGFuIiwibmFtZSI6IkpvcmRhbiBDYXVkaWxsIiwibm9uY2UiOiIxNzgyYmE4Yi0zMjk3LTQxYjgtODJlYS04NDU3NjI1NmI2M2EiLCJvaWQiOiI3NzRkNmY3OC01NDc3LTRmNzEtOGY2ZS1mZWE1OTk1NzdhNTAiLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJqZWctYWRtaW5AeTR0azIub25taWNyb3NvZnQuY29tIiwicmgiOiIwLkFYMEEwNmpIUGJvdFNFU3QwdnZaUHdqNlQxVTF5MFY4cmExQXJVZ3hSQ2pkS3lpY0FJZy4iLCJyb2xlcyI6WyJBdXRoU3VwZXJVc2VyIl0sInN1YiI6IkZLN1hULU5YRGJfblZ1NTlVd2I1THVXWDdFczdNRXE5SzBySlBDZHR4VUUiLCJ0aWQiOiIzZGM3YThkMy0yZGJhLTQ0NDgtYWRkMi1mYmQ5M2YwOGZhNGYiLCJ1dGkiOiJGY0QxUG1vU3RVZWFxQ1lFSkFSVkFBIiwidmVyIjoiMi4wIn0.WjREnuohe3JWAQGULhMvoC3m04QLk9OlbblqaYjkyHbp8QUr4PZywL9T3tZmzF-vQT0Gwt1CBFknKom-1M38LpgLq22KFT9dt5DyO5O7xBRUUmNnWV_Uh5U6fE5oK_O-0UvMEDKC6e_RcvOFwue14N320cNIW6dxc5g2ycdGfXjoQxCQavVurfw3f4StOHV64mCe3i8H1t0k0Qjo6R298i8EJ8AaQ59AATkhBYWmuCaqI-XMMgZxvROgBy85CCusxpROOROoXYXRuain_Ftwaq4nG6Zjr9NaSBCM_hMiOnr0wiOoO7caI1KSgsbOKTw81LboZGc1e4w9rC0lgTuzrA`;
const fakeAccessToken = `eyJ0eXAiOiJKV1QiLCJub25jZSI6IkpHeVdXVUhoaVVsQjBvSDVsSi1mSUVxcW4tdVNMNFNYTjJrc1F2eDkyRzQiLCJhbGciOiJSUzI1NiIsIng1dCI6IjJaUXBKM1VwYmpBWVhZR2FYRUpsOGxWMFRPSSIsImtpZCI6IjJaUXBKM1VwYmpBWVhZR2FYRUpsOGxWMFRPSSJ9.eyJhdWQiOiIwMDAwMDAwMy0wMDAwLTAwMDAtYzAwMC0wMDAwMDAwMDAwMDAiLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC8zZGM3YThkMy0yZGJhLTQ0NDgtYWRkMi1mYmQ5M2YwOGZhNGYvIiwiaWF0IjoxNjYyMDYxNDA4LCJuYmYiOjE2NjIwNjE0MDgsImV4cCI6MTY2MjA2NjE1OSwiYWNjdCI6MCwiYWNyIjoiMSIsImFpbyI6IkFWUUFxLzhUQUFBQTB0RG93LzJwcU1kbkJVcFJTVkZVOUYweVdYRUxiK3dNNmVzMzEwdkNvWXQ0Z0xCVHJORXBScG5ZUkxESnY3aE1DYnFLOTdCUHkvTzVWYmZSL2NLRjVOcVozVk00anhnMW55YUtsM1lWRy93PSIsImFtciI6WyJwd2QiLCJtZmEiXSwiYXBwX2Rpc3BsYXluYW1lIjoiSkVHIiwiYXBwaWQiOiI0NWNiMzU1NS1hZDdjLTQwYWQtYWQ0OC0zMTQ0MjhkZDJiMjgiLCJhcHBpZGFjciI6IjAiLCJmYW1pbHlfbmFtZSI6IkNhdWRpbGwiLCJnaXZlbl9uYW1lIjoiSm9yZGFuIiwiaWR0eXAiOiJ1c2VyIiwiaXBhZGRyIjoiNDcuMTg4LjkwLjExNyIsIm5hbWUiOiJKb3JkYW4gQ2F1ZGlsbCIsIm9pZCI6Ijc3NGQ2Zjc4LTU0NzctNGY3MS04ZjZlLWZlYTU5OTU3N2E1MCIsInBsYXRmIjoiMyIsInB1aWQiOiIxMDAzMjAwMjE5RjI1RTdCIiwicmgiOiIwLkFYMEEwNmpIUGJvdFNFU3QwdnZaUHdqNlR3TUFBQUFBQUFBQXdBQUFBQUFBQUFDY0FJZy4iLCJzY3AiOiJlbWFpbCBwcm9maWxlIFVzZXIuUmVhZCBvcGVuaWQiLCJzdWIiOiJrb1Y0WEdZLXVNcDdNekM0ZFZ2eWNyamFncWVuemxna3FwZ1VRbXBDQXUwIiwidGVuYW50X3JlZ2lvbl9zY29wZSI6Ik5BIiwidGlkIjoiM2RjN2E4ZDMtMmRiYS00NDQ4LWFkZDItZmJkOTNmMDhmYTRmIiwidW5pcXVlX25hbWUiOiJqZWctYWRtaW5AeTR0azIub25taWNyb3NvZnQuY29tIiwidXBuIjoiamVnLWFkbWluQHk0dGsyLm9ubWljcm9zb2Z0LmNvbSIsInV0aSI6IklXRk9jYWFsZ0VxMmNIaGs2LVNlQUEiLCJ2ZXIiOiIxLjAiLCJ3aWRzIjpbIjYyZTkwMzk0LTY5ZjUtNDIzNy05MTkwLTAxMjE3NzE0NWUxMCIsImI3OWZiZjRkLTNlZjktNDY4OS04MTQzLTc2YjE5NGU4NTUwOSJdLCJ4bXNfc3QiOnsic3ViIjoiRks3WFQtTlhEYl9uVnU1OVV3YjVMdVdYN0VzN01FcTlLMHJKUENkdHhVRSJ9LCJ4bXNfdGNkdCI6MTY1OTgyOTc1N30.lLeocFGYbfMDyhlhDn6TUmscQGi8RzkeOiK13gDM2fpaBdprvgtbmxrdkSpPwWIAAVWl-NTEizSq5HUHCbTo1U5AmLffHCow64aSUcnp-qXrsEY-1edkmUzllFf7BBdrba0W6Rmoh28gIxRaXzo6fhzYj0SdaQD-8k-yKZ_rziJMai0DhIHJ5gvB0n77CaCLxPbLBUxUnvXHgHxAXXh51s0b8GWKTNYPWyAc_vDxUlGTswFQMj7NfNcUOFtt_SxcLw07Mj7d2YX3Nj7I00uwdgJXnSImfOvDDokdaaIHDNjAY7fvLNhf2r69tvpxnPj3iVqYtsi7YZ52-C8BlMZVsg`;
const loggedInUserID = '774d6f78-5477-4f71-8f6e-fea599577a50';
const globals = globalThis as any;

beforeEach(async () => {
    const { app, db } = await createApp();
    globals.app = app;
    globals.db = db;
    globals.loggedInUserID = loggedInUserID;
    globals.idToken = fakeIdToken;
    globals.accessToken = fakeAccessToken;

    await globals.db.sequelize.sync({ force: true }).catch((err: any) => console.warn(err));
    await seedTables(globals.db);
    const hook = (method = 'get') => (args: any[]) => {
        // Create hook to automatically use express app created above, and apply the Authorization header to every request.
        // @ts-ignore
        return supertest(globals.app)[method](args).set('Authorization', `Bearer ${fakeIdToken}`);
    };
    globals.request = {
        post: hook('post'),
        get: hook('get'),
        put: hook('put'),
        delete: hook('delete'),
        patch: hook('patch')
    };
});
